build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    my-tests:
      environment:
        php:
          version: 7.1
      services:
        postgres: 10
checks:
  php: true