sudo: false
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

install: travis_retry composer install --no-interaction --prefer-source

script:
# Run PHP-CS Beautifier and Fixer: to format some common non PSR code that can be auto-fixed.
  - vendor/bin/phpcbf --tab-width=4 --encoding=utf-8 --standard=phpcs.xml Core -s
# Run PHP-CS.
  - vendor/bin/phpcs --tab-width=4 --encoding=utf-8 --standard=phpcs.xml Core -s
# Run PHPUnit test.
  - vendor/bin/phpunit --configuration phpunit.xml
matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true