FacturaScripts\Entity\Agent:
    type: entity
    table: agents
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        city:
            type: string
            length: 50
        startDate:
            column: start_date
            type: date
            nullable: true
        endDate:
            column: end_date
            type: date
            nullable: true
        birthday:
            type: date
            nullable: true
        observations:
            type: text
            nullable: true